### ISSUE TITLE
Cannot remove binding using Keymap.update

### ISSUE THREAD

**Issue by Soreine** [marijnh/browserkeymap#3]
Hello,

I am trying to remove some bindings from an existing Keymap, using `Keymap.prototype.update`.

I tried this but it doesn't remove the binding:

``` js
var Keymap = require('browserkeymap');
var keymap = new Keymap({
    'Ctrl-X': function () {}
});
// The keymap does have a Ctrl-X binding
keymap = keymap.update({
    'Ctrl-X': null
});
// The keymap still has the Ctrl-X binding
```

I walked through the code and wonder if [this slice](https://github.com/marijnh/browserkeymap/blob/master/index.js#L111) shouldn't be 

``` diff
- var name = keys.slice(0, i).join(" ")
+ var name = keys.slice(0, i + 1).join(" ")
```

**Comment by marijnh** [comment]
You're entirely right. I've applied your fix and published a 2.0.1
